spring.application.name=api
server.error.include-stacktrace=never
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# ===============================
# LOGS
# ===============================

logging.level.org.springframework.aop.interceptor.AsyncExecutionInterceptor=DEBUG

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:h2:mem:transactions-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# SWAGGER
# ===============================

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


